
import Gals.LexicalError;
import Gals.SemanticError;
import Gals.SyntaticError;
import Gals.Token;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author João Victhor Campos e Lucas Rocha Alves 15-18/11
 */
public class CompilaFrame extends javax.swing.JFrame {
    CompilaControlador controlador;
    String[] colNames = {"Token", "Lexema", "Posicao"};

    /**
     * Creates new form compilaFrame
     */
    public CompilaFrame() {
        initComponents();
        this.controlador = new CompilaControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 650));
        setPreferredSize(new java.awt.Dimension(900, 650));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTextArea1.setColumns(35);
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jTable1.setModel(new DefaultTableModel(colNames, 0));
        jTable1.setEnabled(false);
        jScrollPane3.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel1.add(jScrollPane3, gridBagConstraints);

        jButton1.setText("Análise Léxica");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jButton1, gridBagConstraints);

        jButton2.setText("Análise Sintática");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jButton2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            this.controlador.analisarSintatico(jTextArea1.getText().replaceAll("\r\n", "\n"));
            JOptionPane.showMessageDialog(this, "Codigo correto sintaticamente");
        } catch (LexicalError ex) {
            jTable1.setModel(new DefaultTableModel(colNames, 0));
            int i = JOptionPane.showConfirmDialog(this, ex.getMessage(), "Erro Lexico.",OK_CANCEL_OPTION);
            jTextArea1.requestFocusInWindow();
            jTextArea1.setCaretPosition(ex.getPosition());
        } catch (SyntaticError ex) {
            jTable1.setModel(new DefaultTableModel(colNames, 0));
                        System.out.println(jTextArea1.getText());

            int i = JOptionPane.showConfirmDialog(this, ex.getMessage(), "Erro Sintatico.",OK_CANCEL_OPTION);
            jTextArea1.requestFocusInWindow();
            jTextArea1.setCaretPosition(ex.getPosition());
        } catch (SemanticError ex) {
            jTable1.setModel(new DefaultTableModel(colNames, 0));
            int i = JOptionPane.showConfirmDialog(this, ex.getMessage(), "Erro Semantico.",OK_CANCEL_OPTION);
            jTextArea1.requestFocusInWindow();
            jTextArea1.setCaretPosition(ex.getPosition());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            List<Token> tokens;
            tokens = this.controlador.analisarLexico(jTextArea1.getText().replaceAll("\r\n", "\n"));
            DefaultTableModel newModel = new DefaultTableModel(colNames, 0);
            for(Token t : tokens){
                Object[] o = new Object[3];
                o[0] = t.getId();
                o[1] = t.getLexeme();
                o[2] = t.getPosition();
                newModel.addRow(o);
            }
            jTable1.setModel(newModel);
            JOptionPane.showMessageDialog(this, "Código correto lexicamente");
            
        } catch (LexicalError ex) {
            jTable1.setModel(new DefaultTableModel(colNames, 0));
            int i = JOptionPane.showConfirmDialog(this, ex.getMessage(), "Erro Lexico.",OK_CANCEL_OPTION);
            jTextArea1.requestFocusInWindow();
            jTextArea1.setCaretPosition(ex.getPosition());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompilaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompilaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompilaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompilaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompilaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
